# Generated by Django 2.1.7 on 2019-03-31 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.SlugField(max_length=10, primary_key=True, serialize=False)),
                ('http', models.URLField(max_length=300)),
            ],
        ),
    ]
