# Generated by Django 2.1.7 on 2019-03-31 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='id',
            new_name='short_http',
        ),
    ]
